chkk-io/k8s-cluster-agent

README.md
deploy/helm/chkk-cluster-agent/.helmignore
deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/templates/_helpers.tpl
deploy/helm/chkk-cluster-agent/templates/configmap.yaml
deploy/helm/chkk-cluster-agent/templates/cronjob.yaml
deploy/helm/chkk-cluster-agent/templates/deployment.yaml
deploy/helm/chkk-cluster-agent/templates/job.yaml
deploy/helm/chkk-cluster-agent/templates/rbac.yaml
deploy/helm/chkk-cluster-agent/templates/secret.yaml
deploy/helm/chkk-cluster-agent/templates/serviceaccount.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

Add Cluster Agent v1.0.22

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated Cluster Agent version to `v1.0.23`

Update release version to v1.0.23

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Added default filter rules for Cluster Agent
- Updated image tag and labels to `v1.0.25`

Update Cluster Agent release version to v1.0.25

---

deploy/helm/chkk-cluster-agent/templates/_helpers.tpl
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Removed `chkk-io.` prefix from labels

Remove `chkk-io.` prefix from labels

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated image tag and labels to `v1.0.27`

Update Cluster Agent release version to v1.0.27

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated image tag to `v1.0.29`

Update Cluster Agent release version to v1.0.29

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated image tag to v1.0.30

Update image tag to v1.0.30

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated Cluster Agent image tag to `v1.0.31`

Update Cluster Agent version to v1.0.31

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Update Cluster Agent tag to`v1.0.33`

Update Cluster Agent version to v1.0.33

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated Cluster Agent tag to `v1.0.34`

Update Cluster Agent version to v1.0.34

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated Cluster Agent version to `v1.0.35`

Update Cluster Agent version to v1.0.35

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated Cluster Agent version to `v0.1.0`

Update Cluster Agent version to v0.1.0

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated Cluster Agent version to `v0.1.1`

Update Cluster Agent version to v0.1.1

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated cluster agent version to `v0.1.3`

Update Cluster Agent version to v0.1.3

---

deploy/helm/chkk-cluster-agent/templates/cronjob.yaml
deploy/helm/chkk-cluster-agent/templates/deployment.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated cluster agent version to `v0.1.4`

Update Cluster Agent version to v0.1.4

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Update Helm chart version to `v0.1.4`

Update Helm chart version to v0.1.4

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/templates/_helpers.tpl
deploy/helm/chkk-cluster-agent/templates/configmap.yaml
deploy/helm/chkk-cluster-agent/templates/cronjob.yaml
deploy/helm/chkk-cluster-agent/templates/rbac.yaml
deploy/helm/chkk-cluster-agent/templates/secret.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated Cluster Agent version to `v0.1.5`

Update Cluster Agent version to v0.1.5

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/templates/cronjob.yaml
deploy/helm/chkk-cluster-agent/templates/deployment.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated Chkk K8s Connector version to `v0.1.6`

Update K8s Connector version to v0.1.6

---

deploy/helm/chkk-cluster-agent/Chart.yaml
deploy/helm/chkk-cluster-agent/values.yaml
deploy/k8s-v1.20/chkk-cronjob.yaml
deploy/k8s-v1.21/chkk-cronjob.yaml

- Updated Chkk K8s Connector version to `v0.1.9`

Update K8s Connector version to v0.1.9

---

README.md

**Description**
This repository has been archived and is now read-only. We've transitioned to an operator-based deployment. For updated instructions (available since Sept 2022), please log in at [https://www.chkk.io/](https://www.chkk.io/).

Update readme for repo archive and deployment transition
